ktor:
  application:
    modules:
      - com.flip.ApplicationKt.module
  deployment:
    port: 8091
  development: true
  watch:
    - classes
    - resources
storage:
  driverClassName: "org.postgresql.Driver"
  jdbcURL: "jdbc:postgresql://postgres:5432/flip"
  username: "postgres"
  password: "postgres"
logging:
  seqUrl: "http://seq:5341"